[package]
name = "wake"
version = "0.1.0"
authors = ["Rett Berg <rett@google.com>"]
edition = "2018"
license = "Apache 2.0"

[dependencies]
jsonnet-rs = "0.6.0"
ergo = {git="https://github.com/rust-crates/ergo", branch="path_abs-4.0"}
serde = "1.0.87"
expect_macro = "0.2.1"
semver = "0.9.0"
